# example netlify.toml
[build]
  command = "tinacms build && astro build"
  functions = "netlify/functions"
  publish = "dist"

# [[plugins]] 
#   package = "netlify-plugin-cypress"

#   [plugins.inputs.postBuild]
#     enable = true
  
#   [plugin.inputs]
#     enable = false

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/tina/*"
  to = "/.netlify/functions/tina"
  status = 200
  force = true

[dev]
  command = "npm run dev"
  publish = "public"